---
- name: Do the generic stuff
  ansible.builtin.include_role:
    name: generic-deploy-docker-app
  vars:
    app_name: "{{ dockhand_service_name }}"
    app_directory: "{{ dockhand_app_directory }}"
    app_directories:
      - "{{ dockhand_app_directory }}"
      - "{{ dockhand_data_directory }}"
    app_config_files: []
    app_docker_images:
      - "{{ dockhand_image_tag }}"
