---
- hosts: all
  become: yes
  roles:
    - { role: 'common' }
    - { role: 'cron-jobs' }
    - { role: 'image-desc-bot' }
    - { role: 'update-gcloud-firewall' }

  tasks:
  - name: Congratulations!
    debug:
      msg:
        - "Your home-lab is ready now!"
