---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart postgres
  service:
    name: postgres
    state: restarted

- name: restart pihole
  service:
    name: pihole
    state: restarted

- name: restart traefik
  service:
    name: traefik
    state: restarted

- name: restart jellyfin
  service:
    name: jellyfin
    state: restarted

- name: restart glances
  service:
    name: glances
    state: restarted
