---
- name: Do the generic stuff
  ansible.builtin.include_role:
    name: generic-deploy-docker-app
  vars:
    app_name: "{{ hawser_service_name }}"
    app_directory: "{{ hawser_app_directory }}"
    app_directories:
      - "{{ hawser_app_directory }}"
    app_config_files: []
    app_docker_images:
      - "{{ hawser_image_tag }}"
