---

- name: Install common packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - libffi-dev
      - python3-pip
      - ntp
      - debian-archive-keyring
    allow_unauthenticated: true
    install_recommends: no
    update_cache: true
    state: present
