---

docker_compose_binary: /usr/bin/docker compose
traefik_network_name: proxy
traefik_certresolver_name: letsencrypt
traefik_dynamic_config_dir: '{{ app_root }}/traefik/dynamic'

postgres_port: 5432
earth_host: 192.168.0.210

pihole_ui_port: 6080

valkey_port: 6379
# Valkey database allocations (db 0 = default)
valkey_db_allocations:
  yamtrack: 0
  sure_finance: 1

letsencrypt_cert_location: /etc/letsencrypt
cloudflare_credentials: '/opt/certbot/cloudflare_credentials.ini'
