---

  - name: Create app directory
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ pihole_app_directory }}"
      - "{{ pihole_data_directory }}"
      - "{{ pihole_appdata_directory }}"
      - "{{ pihole_dnsmasq_data_directory }}"
      
  - name: Pull required images from docker hub
    docker_image:
      name: "{{ item }}"
      source: pull
    with_items:
      - "{{ pihole_image_tag }}"
  
  - name: Create docker-compose.yml
    template:
      src: docker-compose.yml.j2
      dest: "{{ pihole_app_directory }}/docker-compose.yml"
    notify: restart {{ pihole_service_name }}
  
  - name: Create app service file
    template:
      src: "{{ pihole_service_name }}.service.j2"
      dest: "{{ pihole_app_directory }}/{{ pihole_service_name }}.service"
    register: pihole_service_file

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
    when: pihole_service_file.changed
  
  - name: Install app service
    file:
      src: "{{ pihole_app_directory }}/{{ pihole_service_name }}.service"
      dest: /etc/systemd/system/{{ pihole_service_name }}.service
      state: link
  
  - name: ensure app starts on a fresh reboot
    service:
      name: "{{ pihole_service_name }}"
      state: started
      enabled: yes
  