---
- name: Do the generic stuff
  ansible.builtin.include_role:
    name: generic-deploy-docker-app
  vars:
    app_name: "{{ yamtrack_service_name }}"
    app_directory: "{{ yamtrack_app_directory }}"
    app_directories:
      - "{{ yamtrack_app_directory }}"
    app_config_files: []
    app_docker_images:
      - "{{ yamtrack_image }}"
