---

- name: Create app directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ influxdb_app_directory }}"
    - "{{ influxdb_data_directory }}"
    - "{{ chronograf_app_directory }}"
    - "{{ chronograf_data_directory }}"

- name: Pull required images from docker hub
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - "{{ influxdb_image_tag }}"
    - "{{ chronograf_image_tag }}"

- name: Create influxdb config file
  template:
    src: "{{ influxdb_config_file }}.j2"
    dest: "{{ influxdb_config_path }}"
  notify: restart influxdb

- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ influxdb_app_directory }}/docker-compose.yml"
  notify: restart influxdb

- name: Create app service file
  template:
    src: influxdb.service.j2
    dest: "{{ influxdb_app_directory }}/influxdb.service"
  register: influx_service_file

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  when: influx_service_file.changed

- name: Install app service
  file:
    src: "{{ influxdb_app_directory }}/influxdb.service"
    dest: /etc/systemd/system/influxdb.service
    state: link

- name: ensure app starts on a fresh reboot
  service:
    name: influxdb
    state: started
    enabled: yes
