
services:
  control-machine:
    image: ghcr.io/smurfpandey/ansible-control-machine:latest
    environment:
      SUDO_PASS: ${SUDO_PASS}
      VAULT_PASS: ${ANSIBLE_VAULT_PASS}
    volumes:
      - .:/ansible/playbooks
      - ~/personal/ssh/id_rsa:/tmp/.ssh/id_rsa
