---

- name: Create app directory in /opt/jobs
  file:
    path: "{{ chitragupta_app_directory }}"
    state: directory

- name: Pull required images from docker hub
  docker_image:
    name: "{{ chitragupta_image_name }}:{{ chitragupta_image_tag }}"
    source: pull

- name: Create docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ chitragupta_app_directory }}/docker-compose.yml"

- name: Create app service file
  template:
    src: "{{ chitragupta_service_name }}.service.j2"
    dest: "{{ chitragupta_app_directory }}/{{ chitragupta_service_name }}.service"
  register: chitragupta_service_file

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  when: chitragupta_service_file.changed
  
- name: Install app service
  file:
    src: "{{ chitragupta_app_directory }}/{{ chitragupta_service_name }}.service"
    dest: /etc/systemd/system/{{ chitragupta_service_name }}.service
    state: link

- name: ensure app starts on a fresh reboot
  service:
    name: "{{ chitragupta_service_name }}"
    state: started
    enabled: yes
