---
- name: Do the generic stuff
  ansible.builtin.include_role:
    name: generic-deploy-docker-app
  vars:
    app_name: "{{ nodecast_tv_service_name }}"
    app_directory: "{{ nodecast_tv_app_directory }}"
    app_directories:
      - "{{ nodecast_tv_app_directory }}"
      - "{{ nodecast_tv_data_directory }}"
    app_config_files: []
    app_docker_images:
      - "{{ nodecast_tv_image }}"
